/-
================================================================
YM_A8_transit_parity.lean   (in-paper name: TransitParity.lean)
================================================================
Certificate 8 (transit parity and the multiplier-weighted
alternation).

Part A (unconditional). On the eight-element quaternion group
Q₈ = {±1, ±i, ±j, ±k}, modelled self-containedly as an explicit
4-component integer structure so that every finite claim is checked
by `decide`: (i) the square of every pure imaginary unit is −1,
so the sign below is independent of the choice of axis; (ii) the
action generated by the inner automorphisms by i and j together
with the centre ⟨−1⟩ decomposes Q₈ into exactly the four degree-2
orbits {±1}, {±i}, {±j}, {±k} — each pair closed under the
generators, connected by the centre, pairwise disjoint, covering
Q₈, of cardinality two.

Part B (conditional). The two geometric identifications of the
prose are encoded as named hypothesis fields: h_lift (each
half-period translation of the torus lifts to the fibre as
right-multiplication by a pure imaginary unit quaternion) and
h_wraps (one full covering period equals two half-period
translations, so the phase of the (n+1)-th period multiplies the
phase of the n-th by the square of the lift). Under exactly these
hypotheses, the cumulative fibre phase over n full covering
periods is (−1)ⁿ.

Part C (unconditional). The single-term evaluation of the
level-two multiplier-weighted generalised sum at modulus two,
K₂(n, −1; 2) = ν̄ · e^{πi(n−1)}, with the multiplier value ν̄ a
parameter, satisfies K₂(n, −1; 2) = (−1)ⁿ for all n ≥ 1 if and
only if ν̄ = −1; with trivial multiplier — the classical sum —
the value is −(−1)ⁿ at every n, so the multiplier-weighted and
classical objects genuinely differ.

Unconditional parts carry no hypotheses; zero `sorry`. No
reference to any gauge group appears in this file.

Build: inside a Mathlib checkout (tag v4.15.0):
  lake env sh -c 'LEAN_PATH="$LEAN_PATH:$PWD" lean TransitParity.lean'
================================================================
-/
import Mathlib.Data.Finset.Card
import Mathlib.Tactic.FinCases
import Mathlib.Tactic.Ring
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Basic

noncomputable section
namespace TransitParity

/-! ## Part A — the quaternionic fibre algebra -/

/-- Integer quaternions, explicit 4-component model. -/
structure H4 where
  a : ℤ
  b : ℤ
  c : ℤ
  d : ℤ
deriving DecidableEq, Repr

namespace H4

/-- The quaternion product. -/
def mul (x y : H4) : H4 :=
  ⟨x.a*y.a - x.b*y.b - x.c*y.c - x.d*y.d,
   x.a*y.b + x.b*y.a + x.c*y.d - x.d*y.c,
   x.a*y.c - x.b*y.d + x.c*y.a + x.d*y.b,
   x.a*y.d + x.b*y.c - x.c*y.b + x.d*y.a⟩

instance : Mul H4 := ⟨mul⟩

def one : H4 := ⟨1, 0, 0, 0⟩
def i : H4 := ⟨0, 1, 0, 0⟩
def j : H4 := ⟨0, 0, 1, 0⟩
def k : H4 := ⟨0, 0, 0, 1⟩
def neg (x : H4) : H4 := ⟨-x.a, -x.b, -x.c, -x.d⟩

/-- Embedding of the centre ℤ. -/
def emb (m : ℤ) : H4 := ⟨m, 0, 0, 0⟩

/-- The six pure imaginary units. -/
def pureUnits : Finset H4 := {i, neg i, j, neg j, k, neg k}

/-- The eight-point quaternion group Q₈. -/
def Q8 : Finset H4 := {one, neg one, i, neg i, j, neg j, k, neg k}

/-- Convention-independence: the square of EVERY pure imaginary
unit is −1, so the choice of axis for the half-period lift does
not affect the sign. -/
theorem sq_pure_unit_eq_neg_one :
    ∀ u ∈ pureUnits, u * u = emb (-1) := by decide

/-- Generators of the action: conjugation by i, conjugation by j
(i⁻¹ = −i, j⁻¹ = −j in Q₈), and the centre. -/
def conjI (x : H4) : H4 := i * x * neg i
def conjJ (x : H4) : H4 := j * x * neg j
def negAct (x : H4) : H4 := neg x

/-- The four candidate orbits. -/
def orb1 : Finset H4 := {one, neg one}
def orbI : Finset H4 := {i, neg i}
def orbJ : Finset H4 := {j, neg j}
def orbK : Finset H4 := {k, neg k}

/-- Each candidate orbit is closed under all three generators
(hence under the generated group). -/
theorem orbits_closed :
    (∀ x ∈ orb1, conjI x ∈ orb1 ∧ conjJ x ∈ orb1 ∧ negAct x ∈ orb1) ∧
    (∀ x ∈ orbI, conjI x ∈ orbI ∧ conjJ x ∈ orbI ∧ negAct x ∈ orbI) ∧
    (∀ x ∈ orbJ, conjI x ∈ orbJ ∧ conjJ x ∈ orbJ ∧ negAct x ∈ orbJ) ∧
    (∀ x ∈ orbK, conjI x ∈ orbK ∧ conjJ x ∈ orbK ∧ negAct x ∈ orbK) := by
  decide

/-- Within each orbit the two elements are connected by a
generator (the centre), so each closed pair is a single orbit,
not two. -/
theorem orbits_connected :
    (∀ x ∈ orb1, negAct x ≠ x) ∧ (∀ x ∈ orbI, negAct x ≠ x) ∧
    (∀ x ∈ orbJ, negAct x ≠ x) ∧ (∀ x ∈ orbK, negAct x ≠ x) := by
  decide

/-- The four orbits partition Q₈: pairwise disjoint, covering,
each of cardinality exactly 2. -/
theorem orbits_partition :
    (orb1 ∪ orbI ∪ orbJ ∪ orbK = Q8) ∧
    (Disjoint orb1 orbI ∧ Disjoint orb1 orbJ ∧ Disjoint orb1 orbK ∧
     Disjoint orbI orbJ ∧ Disjoint orbI orbK ∧ Disjoint orbJ orbK) ∧
    (orb1.card = 2 ∧ orbI.card = 2 ∧ orbJ.card = 2 ∧ orbK.card = 2) := by
  decide

/-! ### Arithmetic helpers -/

theorem emb_neg_one_mul (x : H4) : emb (-1) * x = neg x := by
  show mul (emb (-1)) x = neg x
  simp only [mul, emb, neg, H4.mk.injEq]
  refine ⟨?_, ?_, ?_, ?_⟩ <;> ring

theorem neg_emb (m : ℤ) : neg (emb m) = emb (-m) := by
  simp [neg, emb]

/-! ## Part B — the conditional transit parity -/

/-- The wrap data: the two geometric identifications of the prose,
as named hypothesis fields. -/
structure WrapData where
  /-- the fibre lift of one half-period translation -/
  halfLift : H4
  /-- identification (i): each half-period translation lifts as
      right-multiplication by a pure imaginary unit quaternion -/
  h_lift : halfLift ∈ pureUnits
  /-- the cumulative fibre phase after n full covering periods -/
  coveringPhase : ℕ → H4
  /-- identification (ii): one full covering period equals two
      half-period translations, so each period multiplies the
      cumulative phase by (halfLift · halfLift) -/
  h_wraps : ∀ n, coveringPhase (n + 1) =
    (halfLift * halfLift) * coveringPhase n
  h_zero : coveringPhase 0 = one

/-- **Certificate 8, Part B (the transit parity, conditional).**
Under the two identifications, the cumulative fibre phase over n
full covering periods is (−1)ⁿ. -/
theorem transit_parity (D : WrapData) (n : ℕ) :
    D.coveringPhase n = emb ((-1) ^ n) := by
  induction n with
  | zero => rw [D.h_zero]; rfl
  | succ m ih =>
      rw [D.h_wraps, ih, sq_pure_unit_eq_neg_one D.halfLift D.h_lift,
        emb_neg_one_mul, neg_emb, pow_succ]
      congr 1
      ring

end H4

/-! ## Part C — the multiplier-weighted alternation -/

open Complex Real

/-- The level-two multiplier-weighted generalised sum at modulus
two: the units modulo 2 are {1}, so the sum has the single term
h = 1 (with h·h̄ ≡ −1 (mod 2) giving h̄ = 1), and the value is
ν̄ · e^{2πi(n·1 + (−1)·1)/2} = ν̄ · e^{πi(n−1)}, the multiplier
value ν̄ left as a parameter. -/
def K2c2 (nubar : ℂ) (n : ℕ) : ℂ :=
  nubar * Complex.exp (Real.pi * I * ((n : ℂ) - 1))

/-- The exponential factor evaluates to −(−1)ⁿ for n ≥ 1. -/
theorem exp_eval (n : ℕ) (h : 1 ≤ n) :
    Complex.exp (Real.pi * I * ((n : ℂ) - 1)) = -((-1) ^ n) := by
  obtain ⟨m, rfl⟩ := Nat.exists_eq_add_of_le h
  have h1 : ((1 + m : ℕ) : ℂ) - 1 = (m : ℂ) := by push_cast; ring
  rw [h1, show Real.pi * I * (m : ℂ) = (m : ℂ) * (Real.pi * I) by ring,
     Complex.exp_nat_mul, Complex.exp_pi_mul_I]
  rw [pow_add, pow_one]
  ring

/-- **Certificate 8, Part C (the characterisation).** The
alternation K₂(n, −1; 2) = (−1)ⁿ holds for all n ≥ 1 if and only
if the multiplier value ν̄ equals −1. -/
theorem characterisation (nubar : ℂ) :
    (∀ n : ℕ, 1 ≤ n → K2c2 nubar n = (-1) ^ n) ↔ nubar = -1 := by
  constructor
  · intro h
    have h1 := h 1 le_rfl
    simp only [K2c2] at h1
    rw [exp_eval 1 le_rfl] at h1
    simpa using h1
  · intro h n hn
    simp only [K2c2, h, exp_eval n hn]
    ring

/-- With trivial multiplier — the classical sum — the value is
−(−1)ⁿ at every n ≥ 1: the multiplier-weighted and classical
objects genuinely differ, by an overall sign at every n. -/
theorem classical_sum_differs (n : ℕ) (hn : 1 ≤ n) :
    K2c2 1 n = -((-1) ^ n) := by
  simp only [K2c2, one_mul]
  exact exp_eval n hn

end TransitParity